import 'package:mts/core/utils/log_utils.dart';

/// Helper class for registering all Hive adapters
/// Adapters are generated by build_runner for @HiveType models
class HiveAdapterRegistration {
  /// Register all Hive type adapters
  /// Call this BEFORE opening boxes in main.dart
  ///
  /// Note: This requires running:
  /// ```bash
  /// flutter pub run build_runner build --delete-conflicting-outputs
  /// ```
  ///
  /// After you add @HiveType annotations to models
  static Future<void> registerAllAdapters() async {
    try {
      await LogUtils.info('Starting Hive adapter registration...');

      // Register adapters here as you add @HiveType to models
      // Example format:
      // Hive.registerAdapter(CustomerModelAdapter());
      // Hive.registerAdapter(ItemModelAdapter());
      // etc.

      // For now, we're using Map<String, dynamic> for caching
      // which doesn't require adapters. As you transition to typed
      // Hive models, uncomment and add adapter registrations below.

      // ============================================
      // CUSTOMER & USER ADAPTERS (when implemented)
      // ============================================
      // Hive.registerAdapter(CustomerModelAdapter());
      // Hive.registerAdapter(UserModelAdapter());
      // Hive.registerAdapter(StaffModelAdapter());

      // ============================================
      // ITEM ADAPTERS (when implemented)
      // ============================================
      // Hive.registerAdapter(ItemModelAdapter());
      // Hive.registerAdapter(ItemModifierModelAdapter());
      // Hive.registerAdapter(ItemTaxModelAdapter());
      // Hive.registerAdapter(ModifierModelAdapter());
      // Hive.registerAdapter(ModifierOptionModelAdapter());
      // Hive.registerAdapter(OrderOptionModelAdapter());

      // ============================================
      // SALE ADAPTERS (when implemented)
      // ============================================
      // Hive.registerAdapter(SaleModelAdapter());
      // Hive.registerAdapter(SaleItemModelAdapter());
      // Hive.registerAdapter(SaleModifierModelAdapter());
      // Hive.registerAdapter(SaleModifierOptionModelAdapter());
      // Hive.registerAdapter(SaleVariantOptionModelAdapter());

      // ============================================
      // PAYMENT & DISCOUNT ADAPTERS (when implemented)
      // ============================================
      // Hive.registerAdapter(PaymentTypeModelAdapter());
      // Hive.registerAdapter(DiscountModelAdapter());
      // Hive.registerAdapter(DiscountItemModelAdapter());

      // ============================================
      // TAX & OUTLET ADAPTERS (when implemented)
      // ============================================
      // Hive.registerAdapter(TaxModelAdapter());
      // Hive.registerAdapter(OutletModelAdapter());
      // Hive.registerAdapter(OutletTaxModelAdapter());

      // ============================================
      // INVENTORY ADAPTERS (when implemented)
      // ============================================
      // Hive.registerAdapter(InventoryModelAdapter());
      // Hive.registerAdapter(InventoryTransactionModelAdapter());

      // ============================================
      // OTHER ADAPTERS (when implemented)
      // ============================================
      // Hive.registerAdapter(ShiftModelAdapter());
      // Hive.registerAdapter(SupplierModelAdapter());
      // Hive.registerAdapter(CategoryModelAdapter());

      await LogUtils.info('Hive adapter registration complete');
    } catch (e) {
      await LogUtils.error('Error registering Hive adapters', e);
      rethrow;
    }
  }

  /// Guide for implementing Hive adapters with your models
  ///
  /// STEP 1: Add @HiveType annotation to your model class
  /// ```dart
  /// import 'package:hive/hive.dart';
  ///
  /// part 'customer_model.g.dart';
  ///
  /// @HiveType(typeId: 0)
  /// class CustomerModel {
  ///   @HiveField(0)
  ///   final String? id;
  ///
  ///   @HiveField(1)
  ///   final String? name;
  ///
  ///   // ... other fields
  /// }
  /// ```
  ///
  /// STEP 2: Assign unique typeIds (0-255)
  /// - CustomerModel: 0
  /// - ItemModel: 1
  /// - SaleModel: 2
  /// - SaleItemModel: 3
  /// - StaffModel: 4
  /// - UserModel: 5
  /// - OutletModel: 6
  /// - PaymentTypeModel: 7
  /// - DiscountModel: 8
  /// - TaxModel: 9
  /// - etc.
  ///
  /// STEP 3: Run build runner to generate adapters
  /// ```bash
  /// flutter pub run build_runner build --delete-conflicting-outputs
  /// ```
  ///
  /// STEP 4: Register adapters in this file
  /// ```dart
  /// Hive.registerAdapter(CustomerModelAdapter());
  /// Hive.registerAdapter(ItemModelAdapter());
  /// // ... etc
  /// ```
  ///
  /// STEP 5: Import generated adapters at top of this file
  /// ```dart
  /// import 'package:mts/data/models/customer/customer_model.g.dart';
  /// import 'package:mts/data/models/item/item_model.g.dart';
  /// // ... etc
  /// ```

  /// Type IDs for Hive models (unique per model)
  /// Keep this list updated as you add typed models
  static const Map<String, int> typeIdMapping = {
    'CustomerModel': 0,
    'ItemModel': 1,
    'SaleModel': 2,
    'SaleItemModel': 3,
    'StaffModel': 4,
    'UserModel': 5,
    'OutletModel': 6,
    'PaymentTypeModel': 7,
    'DiscountModel': 8,
    'TaxModel': 9,
    'SaleModifierModel': 10,
    'SaleModifierOptionModel': 11,
    'SaleVariantOptionModel': 12,
    'ModifierModel': 13,
    'ModifierOptionModel': 14,
    'OrderOptionModel': 15,
    'CategoryModel': 16,
    'SupplierModel': 17,
    'ShiftModel': 18,
    'InventoryModel': 19,
    'InventoryTransactionModel': 20,
  };

  /// Get next available typeId
  static int getNextTypeId() {
    return typeIdMapping.values.fold(0, (max, val) => val > max ? val : max) +
        1;
  }
}
