import 'dart:convert';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/adapters.dart';
import 'package:mts/core/services/hive_sync_helper.dart';
import 'package:mts/core/storage/hive_box_manager.dart';
import 'package:mts/core/storage/secure_storage_api.dart';
import 'package:mts/data/datasources/local/database_helpers.dart';
import 'package:mts/data/repositories/local/local_pending_changes_repository_impl.dart';
import 'package:mts/core/utils/log_utils.dart';
import 'package:mts/data/datasources/local/database_helpers_interface.dart';
import 'package:mts/data/models/pending_changes/pending_changes_model.dart';
import 'package:mts/data/models/pos_device/pos_device_model.dart';
import 'package:mts/domain/repositories/local/device_repository.dart';
import 'package:mts/domain/repositories/local/pending_changes_repository.dart';
import 'package:sqflite/sqflite.dart';

final deviceBoxProvider = Provider<Box<Map>>((ref) {
  return HiveBoxManager.getValidatedBox(PosDeviceModel.modelBoxName);
});

/// ================================
/// Provider for Local Repository
/// ================================
final deviceLocalRepoProvider = Provider<LocalDeviceRepository>((ref) {
  return LocalDeviceRepositoryImpl(
    dbHelper: ref.read(databaseHelpersProvider),
    pendingChangesRepository: ref.read(pendingChangesLocalRepoProvider),
    secureStorageApi: ref.read(secureStorageApiProvider),
    hiveBox: ref.read(deviceBoxProvider),
  );
});

/// ================================
/// Local Repository Implementation
/// ================================
/// Implementation of [LocalDeviceRepository] that uses local database
class LocalDeviceRepositoryImpl implements LocalDeviceRepository {
  final IDatabaseHelpers _dbHelper;
  final LocalPendingChangesRepository _pendingChangesRepository;
  final SecureStorageApi _secureStorageApi;
  final Box<Map> _hiveBox;

  /// Database table and column names
  static const String tableName = 'pos_devices';
  static const String cId = 'id';
  static const String outletId = 'outlet_id';
  static const String name = 'name';
  static const String code = 'code';
  static const String nextRnReceipt = 'next_rn_receipt';
  static const String isActive = 'is_active';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';

  /// Constructor
  LocalDeviceRepositoryImpl({
    required IDatabaseHelpers dbHelper,
    required LocalPendingChangesRepository pendingChangesRepository,
    required SecureStorageApi secureStorageApi,
    required Box<Map> hiveBox,
  }) : _dbHelper = dbHelper,
       _secureStorageApi = secureStorageApi,
       _pendingChangesRepository = pendingChangesRepository,
       _hiveBox = hiveBox;

  /// Create the device table in the database
  static Future<void> createTable(Database db) async {
    String rows = '''
      $cId TEXT PRIMARY KEY,
      $outletId TEXT NULL,
      $name TEXT NULL,
      $code TEXT NULL,
      $nextRnReceipt INTEGER DEFAULT 1,
      $isActive INTEGER DEFAULT 0,
      $createdAt TIMESTAMP DEFAULT NULL,
      $updatedAt TIMESTAMP DEFAULT NULL
    ''';
    await IDatabaseHelpers.createTable(tableName, rows, db);
  }

  @override
  Future<int> insert(
    PosDeviceModel model, {
    required bool isInsertToPending,
  }) async {
    // Note: id is auto-generated by SQLite (INTEGER PRIMARY KEY)
    model.createdAt = DateTime.now();
    model.updatedAt = DateTime.now();

    try {
      // Insert to SQLite
      int result = await _dbHelper.insertDb(tableName, model.toJson());

      // Insert to Hive
      await _hiveBox.put(model.id!.toString(), model.toJson());

      if (isInsertToPending) {
        await _insertPending(model, 'created');
      }

      return result;
    } catch (e) {
      await LogUtils.error('Error inserting device', e);
      rethrow;
    }
  }

  @override
  Future<int> update(
    PosDeviceModel model, {
    required bool isInsertToPending,
  }) async {
    model.updatedAt = DateTime.now();

    try {
      // Update SQLite
      int result = await _dbHelper.updateDb(tableName, model.toJson());

      // Update Hive
      await _hiveBox.put(model.id!.toString(), model.toJson());

      if (isInsertToPending) {
        await _insertPending(model, 'updated');
      }

      return result;
    } catch (e) {
      await LogUtils.error('Error updating device', e);
      rethrow;
    }
  }

  @override
  Future<int> delete(String id, {required bool isInsertToPending}) async {
    // Get single item efficiently instead of fetching all
    final model =
        HiveSyncHelper.getById(
          box: _hiveBox,
          id: id,
          fromJson: (json) => PosDeviceModel.fromJson(json),
        ) ??
        PosDeviceModel(id: id);

    try {
      // Delete from SQLite
      int result = await _dbHelper.deleteDb(tableName, id);

      // Delete from Hive
      await _hiveBox.delete(id);

      if (isInsertToPending) {
        await _insertPending(model, 'deleted');
      }

      return result;
    } catch (e) {
      await LogUtils.error('Error deleting device', e);
      rethrow;
    }
  }

  // ==================== Bulk Operations ====================

  @override
  Future<bool> upsertBulk(
    List<PosDeviceModel> list, {
    required bool isInsertToPending,
  }) async {
    try {
      Database db = await _dbHelper.database;
      final batch = db.batch();
      final List<PendingChangesModel> pendingList = [];

      for (var model in list) {
        // Note: id is auto-generated by SQLite (INTEGER PRIMARY KEY)
        model.createdAt ??= DateTime.now();
        model.updatedAt ??= DateTime.now();

        batch.insert(
          tableName,
          model.toJson(),
          conflictAlgorithm: ConflictAlgorithm.replace,
        );

        if (isInsertToPending) {
          pendingList.add(
            PendingChangesModel(
              operation: 'created',
              modelName: PosDeviceModel.modelName,
              modelId: model.id!.toString(),
              data: jsonEncode(model.toJson()),
            ),
          );
        }
      }

      await batch.commit(noResult: true);

      // Bulk insert to Hive
      final dataMap = <dynamic, Map<dynamic, dynamic>>{};
      for (var model in list) {
        if (model.id != null) {
          dataMap[model.id!] = model.toJson();
        }
      }
      await _hiveBox.putAll(dataMap);

      for (var pending in pendingList) {
        await _pendingChangesRepository.insert(pending);
      }

      return true;
    } catch (e) {
      await LogUtils.error('Error bulk inserting devices', e);
      return false;
    }
  }

  @override
  Future<bool> replaceAllData(
    List<PosDeviceModel> newData, {
    bool isInsertToPending = false,
  }) async {
    try {
      final db = await _dbHelper.database;
      await db.delete(tableName); // Delete all rows from SQLite
      await _hiveBox.clear();
      // Clear Hive
      return await upsertBulk(newData, isInsertToPending: isInsertToPending);
    } catch (e) {
      await LogUtils.error('Error replacing all devices', e);
      return false;
    }
  }

  /// Get single model by ID (Hive-first, fallback to SQLite)
  Future<PosDeviceModel?> getById(String id) async {
    // Try Hive cache first
    final hiveModel = HiveSyncHelper.getById(
      box: _hiveBox,
      id: id,
      fromJson: (json) => PosDeviceModel.fromJson(json),
    );
    if (hiveModel != null) {
      return hiveModel;
    }

    // Fallback to SQLite
    final map = await _dbHelper.readDbById(tableName, id);
    if (map != null) {
      return PosDeviceModel.fromJson(map);
    }
    return null;
  }

  // ==================== Helper Methods ====================

  Future<void> _insertPending(PosDeviceModel model, String operation) async {
    final pending = PendingChangesModel(
      operation: operation,
      modelName: PosDeviceModel.modelName,
      modelId: model.id!.toString(),
      data: jsonEncode(model.toJson()),
    );
    await _pendingChangesRepository.insert(pending);
  }

  /// Delete multiple device records
  @override
  Future<bool> deleteBulk(
    List<PosDeviceModel> list, {
    required bool isInsertToPending,
  }) async {
    try {
      for (var device in list) {
        if (device.id != null) {
          await delete(
            device.id.toString(),
            isInsertToPending: isInsertToPending,
          );
        }
      }
      return true;
    } catch (e) {
      await LogUtils.error('Error deleting bulk devices', e);
      return false;
    }
  }

  @override
  Future<List<PosDeviceModel>> getListDeviceModel() async {
    // ✅ Try Hive first
    final hiveList = HiveSyncHelper.getListFromBox(
      box: _hiveBox,
      fromJson: (json) => PosDeviceModel.fromJson(json),
    );

    if (hiveList.isNotEmpty) {
      return hiveList;
    }

    // Fallback to SQLite
    final List<Map<String, dynamic>> maps = await _dbHelper.readDb(tableName);
    return List.generate(maps.length, (index) {
      return PosDeviceModel.fromJson(maps[index]);
    });
  }

  /// Get a device record by ID
  @override
  Future<PosDeviceModel> getDeviceById(String idDevice) async {
    // Try Hive cache first
    final fromHive = HiveSyncHelper.getById<PosDeviceModel>(
      box: _hiveBox,
      id: idDevice,
      fromJson: (json) => PosDeviceModel.fromJson(json),
    );
    if (fromHive != null) return fromHive;

    // Fallback to SQLite
    Database db = await _dbHelper.database;
    List<Map<String, dynamic>> maps = await db.query(
      tableName,
      where: '$cId = ?',
      whereArgs: [idDevice],
    );

    if (maps.isNotEmpty) {
      return PosDeviceModel.fromJson(maps.first);
    }

    return PosDeviceModel();
  }

  @override
  Future<PosDeviceModel> getLatestDeviceModel() async {
    // Get device ID from secure storage (persisted device info)
    Map<String, dynamic> posDeviceJson =
        await _secureStorageApi.readObject('device') ?? {};
    PosDeviceModel posDeviceModel = PosDeviceModel.fromJson(posDeviceJson);

    if (posDeviceModel.id == null || posDeviceModel.id!.isEmpty) {
      return PosDeviceModel();
    }

    // Try Hive cache first for latest data (includes nextRnReceipt)
    final fromHive = HiveSyncHelper.getById<PosDeviceModel>(
      box: _hiveBox,
      id: posDeviceModel.id!,
      fromJson: (json) => PosDeviceModel.fromJson(json),
    );
    if (fromHive != null) return fromHive;

    // Fallback to SQLite
    Database db = await _dbHelper.database;
    final List<Map<String, dynamic>> maps = await db.query(
      tableName,
      where: '$cId = ?',
      whereArgs: [posDeviceModel.id],
    );
    if (maps.isNotEmpty) {
      return PosDeviceModel.fromJson(maps.first);
    } else {
      return PosDeviceModel();
    }
  }
}
