import 'dart:convert';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/adapters.dart';
import 'package:mts/core/services/hive_sync_helper.dart';
import 'package:mts/core/storage/hive_box_manager.dart';
import 'package:mts/data/datasources/local/database_helpers.dart';
import 'package:mts/data/repositories/local/local_pending_changes_repository_impl.dart';
import 'package:mts/core/utils/log_utils.dart';
import 'package:mts/data/datasources/local/database_helpers_interface.dart';
import 'package:mts/data/models/customer/customer_model.dart';
import 'package:mts/data/models/pending_changes/pending_changes_model.dart';
import 'package:mts/domain/repositories/local/customer_repository.dart';
import 'package:mts/domain/repositories/local/pending_changes_repository.dart';
import 'package:sqflite/sqflite.dart';

final customerBoxProvider = Provider<Box<Map>>((ref) {
  return HiveBoxManager.getValidatedBox(CustomerModel.modelBoxName);
});

/// ================================
/// Provider for Local Repository
/// ================================
final customerLocalRepoProvider = Provider<LocalCustomerRepository>((ref) {
  return LocalCustomerRepositoryImpl(
    dbHelper: ref.read(databaseHelpersProvider),
    pendingChangesRepository: ref.read(pendingChangesLocalRepoProvider),
    hiveBox: ref.read(customerBoxProvider),
  );
});

/// ================================
/// Local Repository Implementation
/// ================================
/// Implementation of [LocalCustomerRepository] that uses local database
class LocalCustomerRepositoryImpl implements LocalCustomerRepository {
  final IDatabaseHelpers _dbHelper;
  final LocalPendingChangesRepository _pendingChangesRepository;
  final Box<Map> _hiveBox;

  /// Database table and column names
  static const String cId = 'id';
  static const String companyId = 'company_id';
  static const String name = 'name';
  static const String phoneNo = 'phone_no';
  static const String email = 'email';
  static const String address = 'address';
  static const String postcode = 'postcode';
  static const String note = 'note';
  static const String worldCityId = 'world_city_id';
  static const String worldDivisionId = 'world_division_id';
  static const String worldCountryId = 'world_country_id';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';
  static const String tableName = 'customers';

  /// Constructor
  LocalCustomerRepositoryImpl({
    required IDatabaseHelpers dbHelper,
    required LocalPendingChangesRepository pendingChangesRepository,
    required Box<Map> hiveBox,
  }) : _dbHelper = dbHelper,
       _pendingChangesRepository = pendingChangesRepository,
       _hiveBox = hiveBox;

  /// Create the customer table in the database
  static Future<void> createTable(Database db) async {
    String rows = '''
      $cId TEXT PRIMARY KEY,
      $companyId TEXT NULL,
      $name TEXT NULL,
      $phoneNo TEXT NULL,
      $email TEXT NULL,
      $address TEXT NULL,
      $postcode TEXT NULL,
      $note TEXT NULL,
      $worldCityId TEXT NULL,
      $worldDivisionId TEXT NULL,
      $worldCountryId TEXT NULL,
      $createdAt TIMESTAMP DEFAULT NULL,
      $updatedAt TIMESTAMP DEFAULT NULL
    ''';

    await IDatabaseHelpers.createTable(tableName, rows, db);
  }

  @override
  Future<int> insert(
    CustomerModel model, {
    required bool isInsertToPending,
  }) async {
    // Note: id is auto-generated by SQLite (INTEGER PRIMARY KEY)
    model.createdAt = DateTime.now();
    model.updatedAt = DateTime.now();

    try {
      // Insert to SQLite
      int result = await _dbHelper.insertDb(tableName, model.toJson());

      // Insert to Hive
      await _hiveBox.put(model.id!.toString(), model.toJson());

      if (isInsertToPending) {
        await _insertPending(model, 'created');
      }

      return result;
    } catch (e) {
      await LogUtils.error('Error inserting customer', e);
      rethrow;
    }
  }

  @override
  Future<int> update(
    CustomerModel model, {
    required bool isInsertToPending,
  }) async {
    model.updatedAt = DateTime.now();

    try {
      // Update SQLite
      int result = await _dbHelper.updateDb(tableName, model.toJson());

      // Update Hive
      await _hiveBox.put(model.id!.toString(), model.toJson());

      if (isInsertToPending) {
        await _insertPending(model, 'updated');
      }

      return result;
    } catch (e) {
      await LogUtils.error('Error updating customer', e);
      rethrow;
    }
  }

  @override
  Future<int> delete(String id, {required bool isInsertToPending}) async {
    // Get single item efficiently instead of fetching all
    final model =
        HiveSyncHelper.getById(
          box: _hiveBox,
          id: id,
          fromJson: (json) => CustomerModel.fromJson(json),
        ) ??
        CustomerModel(id: id);

    try {
      // Delete from SQLite
      int result = await _dbHelper.deleteDb(tableName, id);

      // Delete from Hive
      await _hiveBox.delete(id);

      if (isInsertToPending) {
        await _insertPending(model, 'deleted');
      }

      return result;
    } catch (e) {
      await LogUtils.error('Error deleting customer', e);
      rethrow;
    }
  }

  // ==================== Bulk Operations ====================

  @override
  Future<bool> upsertBulk(
    List<CustomerModel> list, {
    required bool isInsertToPending,
  }) async {
    try {
      Database db = await _dbHelper.database;
      final batch = db.batch();
      final List<PendingChangesModel> pendingList = [];

      for (var model in list) {
        // Note: id is auto-generated by SQLite (INTEGER PRIMARY KEY)
        model.createdAt ??= DateTime.now();
        model.updatedAt ??= DateTime.now();

        batch.insert(
          tableName,
          model.toJson(),
          conflictAlgorithm: ConflictAlgorithm.replace,
        );

        if (isInsertToPending) {
          pendingList.add(
            PendingChangesModel(
              operation: 'created',
              modelName: CustomerModel.modelName,
              modelId: model.id!.toString(),
              data: jsonEncode(model.toJson()),
            ),
          );
        }
      }

      await batch.commit(noResult: true);

      // Bulk insert to Hive
      final dataMap = <dynamic, Map<dynamic, dynamic>>{};
      for (var model in list) {
        if (model.id != null) {
          dataMap[model.id!] = model.toJson();
        }
      }
      await _hiveBox.putAll(dataMap);

      for (var pending in pendingList) {
        await _pendingChangesRepository.insert(pending);
      }

      return true;
    } catch (e) {
      await LogUtils.error('Error bulk inserting customers', e);
      return false;
    }
  }

  @override
  Future<bool> replaceAllData(
    List<CustomerModel> newData, {
    bool isInsertToPending = false,
  }) async {
    try {
      final db = await _dbHelper.database;
      await db.delete(tableName); // Delete all rows from SQLite
      await _hiveBox.clear(); // Clear Hive
      return await upsertBulk(newData, isInsertToPending: isInsertToPending);
    } catch (e) {
      await LogUtils.error('Error replacing all customers', e);
      return false;
    }
  }

  // ==================== Query Operations ====================

  Future<List<CustomerModel>> getListCustomers() async {
    // Try Hive cache first
    final hiveList = HiveSyncHelper.getListFromBox(
      box: _hiveBox,
      fromJson: (json) => CustomerModel.fromJson(json),
    );
    if (hiveList.isNotEmpty) {
      return hiveList;
    }

    // Fallback to SQLite
    final maps = await _dbHelper.readDb(tableName);
    return maps.map((json) => CustomerModel.fromJson(json)).toList();
  }

  /// Get single model by ID (Hive-first, fallback to SQLite)
  Future<CustomerModel?> getById(String id) async {
    // Try Hive cache first
    final hiveModel = HiveSyncHelper.getById(
      box: _hiveBox,
      id: id,
      fromJson: (json) => CustomerModel.fromJson(json),
    );
    if (hiveModel != null) {
      return hiveModel;
    }

    // Fallback to SQLite
    final map = await _dbHelper.readDbById(tableName, id);
    if (map != null) {
      return CustomerModel.fromJson(map);
    }
    return null;
  }

  // ==================== Delete Operations ====================

  @override
  Future<bool> deleteAll() async {
    try {
      // Delete from SQLite
      final db = await _dbHelper.database;
      await db.delete(tableName);

      // Delete from Hive
      await _hiveBox.clear();

      return true;
    } catch (e) {
      await LogUtils.error('Error deleting all customers', e);
      return false;
    }
  }

  // ==================== Helper Methods ====================

  Future<void> _insertPending(CustomerModel model, String operation) async {
    final pending = PendingChangesModel(
      operation: operation,
      modelName: CustomerModel.modelName,
      modelId: model.id!.toString(),
      data: jsonEncode(model.toJson()),
    );
    await _pendingChangesRepository.insert(pending);
  }

  /// Delete multiple city records
  @override
  Future<bool> deleteBulk(
    List<CustomerModel> listCity, {
    required bool isInsertToPending,
  }) async {
    try {
      for (var city in listCity) {
        if (city.id != null) {
          await delete(
            city.id.toString(),
            isInsertToPending: isInsertToPending,
          );
        }
      }
      return true;
    } catch (e) {
      await LogUtils.error('Error deleting bulk cities', e);
      return false;
    }
  }

  @override
  Future<List<CustomerModel>> getListCustomerModel() async {
    // ✅ Try Hive first
    final hiveList = HiveSyncHelper.getListFromBox(
      box: _hiveBox,
      fromJson: (json) => CustomerModel.fromJson(json),
    );

    if (hiveList.isNotEmpty) {
      return hiveList;
    }

    // Fallback to SQLite
    final List<Map<String, dynamic>> maps = await _dbHelper.readDb(tableName);
    return List.generate(maps.length, (index) {
      return CustomerModel.fromJson(maps[index]);
    });
  }

  /// Get a city record by ID
  @override
  Future<CustomerModel?> getCustomerModelById(String cityId) async {
    // Try Hive cache first
    final fromHive = HiveSyncHelper.getById<CustomerModel>(
      box: _hiveBox,
      id: cityId,
      fromJson: (json) => CustomerModel.fromJson(json),
    );
    if (fromHive != null) return fromHive;

    // Fallback to SQLite
    Database db = await _dbHelper.database;
    List<Map<String, dynamic>> maps = await db.query(
      tableName,
      where: '$cId = ?',
      whereArgs: [cityId],
    );

    if (maps.isNotEmpty) {
      return CustomerModel.fromJson(maps.first);
    }

    return null;
  }
}
